### ISSUE TITLE
Add example on how to create a profile

### ISSUE THREAD

**Issue by amenk** [SC-Networks/evalanche-soap-api-connector#103]
I think it is one of the most common use cases, to add profiles to Evalanche, so an example would be nice :)

**Comment by s1de21** [comment]
Hey,

you see examples here: https://github.com/SC-Networks/evalanche-soap-api-connector/blob/master/docs/index.md

The profile example is here: https://github.com/SC-Networks/evalanche-soap-api-connector/blob/master/docs/profile.md

and this is how the hashmap works: 

```
$HashMap = new \Scn\EvalancheSoapStruct\Struct\Generic\HashMap([
    new \Scn\EvalancheSoapStruct\Struct\Generic\HashMapItem('field_to_update', 'updated_field_value'),
    new \Scn\EvalancheSoapStruct\Struct\Generic\HashMapItem('next_field_to_update', 'next_updated_field_value')
]);
```

**Comment by amenk** [comment]
Awesome :) thanks for the quick response. What about hash map items for multi-select-attributes?

**Comment by WorksDev** [comment]
@s1de21 thanks for your Answer ;)

**Comment by WorksDev** [comment]
Hi @amenk 

similar behaviour:

`
new \Scn\EvalancheSoapStruct\Struct\Generic\HashMapItem('field_to_update', 'updated_field_value|other_updated_field_value'),
`

**Comment by amenk** [comment]
the values are the IDs, right? We have to pull them from the pool then and map or cleartext values to the IDs? Or this there something built-in as well?

**Comment by WorksDev** [comment]
@amenk 
Sorry for the late answer - yes these are Ids - if you getAttributesByPool from the PoolClient - both the Ids and the cleartext values are available.

**Comment by s1de21** [comment]
Sorry i had problems verifying my mail, 

@WorksDev i think it would be nice to have a little hashmap example  in this doc: https://github.com/SC-Networks/evalanche-soap-api-connector/blob/master/docs/index.md 

Just tell me if i should do it.

**Comment by usox** [comment]
@s1de21 Please feel free to submit a pull request. I'm ok with the docu main page - if we find a better place, we can relocate it anyway.
