### ISSUE TITLE
Can we or do we need to close connections?

### ISSUE THREAD

**Issue by amenk** [SC-Networks/evalanche-soap-api-connector#147]
We are using the package in a Laravel queue job which updates data on Evalanche.

We noticed that after a while, lots of connections pile up on the server to scnem2.com / 80.190.118.178 which is the Evalanche API 

    # netstat -anp|grep 80.190.118.178|wc -l
    679

When we restart or queue runner, the connections are closed properly but start piling up again:

They look like this:

    # netstat -anp|grep 80.190.118.178
    tcp       32      0 <ourip>:46872     80.190.118.178:443      CLOSE_WAIT  21483/php       
    tcp       32      0 <ourip>:46834     80.190.118.178:443      CLOSE_WAIT  21483/php       
    tcp       32      0 <ourip>:46850     80.190.118.178:443      CLOSE_WAIT  21483/php

Can this be avoided?

**Comment by amenk** [comment]
[This should help](https://stackoverflow.com/a/54740346/288568) but is not supported by this package. Shall we make a PR and set keep_alive always to false?

**Comment by usox** [comment]
Hi @amenk 

Thanks, this is really interesting. We will check it out next week and test it on our soap testing environment which also uses the connector (which performs hundreds of sequential soap calls). Maybe we should consider to make it configurable by the user - but we'll run some tests and benchmarks first.

**Comment by usox** [comment]
Good morning.

I checked it out now and observed an increased performance in our environment (our test suite runs about 15-20% faster) - so I'll give it a go.
After a short discussion with the team, we decided to choose another approach for the implementation, so I'm going to close your PR. The changes will be available in master later today or tomorrow - so you can check it out then.

**Comment by amenk** [comment]
looks good, keep_alive = false will not be default for B/C, right? But we can set it our selves. Please ping me when the new version is tagged

**Comment by usox** [comment]
> looks good, keep_alive = false will not be default for B/C, right? But we can set it our selves.
Correct, don't want to change the behavior within a minor release.

> Please ping me when the new version is tagged.
Well, it is merged now - so you can try it out using `dev-master`. I'll check some other minor changes before releasing the next version but it won't take long.

**Comment by amenk** [comment]
We'll wait for the tag to use a clean release :)

**Comment by usox** [comment]
@amenk 1.8 out now :)
