### ISSUE TITLE
Fetching a profile using the encrypted UID

### ISSUE THREAD

**Issue by LosHawlos** [SC-Networks/evalanche-soap-api-connector#151]
Hi,

I currently fail to fetch profiles using the encrypted UID.

The help center describes the UID in this document
https://help.evalanche.cloud/hc/en-us/articles/360026462232-SOAP-API-Overview
to be mapped to the virtual attribute "SID".
Which is true as I can fetch this attribute when reading out profiles.

But: I can not use getByKey() from the ProfileClient because it throws an exception:
Unknown pool attribute: SID

An other possible way could be using getById instead:

The help center describing getById of the ProfileClient
https://help.evalanche.cloud/hc/en-us/articles/360042265151-SOAP-Profile
says:
string profile_id: ID or UID of the profile to be searched

BUT: That is not possible using this api connector because of the paramater is specified as int:
https://github.com/SC-Networks/evalanche-soap-api-connector/blob/aa7a43369bea188eaafb3aa7dcbce60b7176fe50/src/Client/Profile/ProfileClient.php#L154
so that the UID can not be passed.

Could either getByKey or getById be fixed so that I can use the UID?

Thanks.

**Comment by WorksDev** [comment]
Hi @LosHawlos,

thanks for pointing that out.

> But: I can not use getByKey() from the ProfileClient because it throws an exception:
Unknown pool attribute: SID 

Correct it is a virtual not existing attribute, therefore also not retrievable in this way.

> says:
string profile_id: ID or UID of the profile to be searched
BUT: That is not possible using this api connector because of the paramater is specified as int

Fix is in work.

**Comment by usox** [comment]
Hi @LosHawlos 

The issue has been fixed, a 1.8.1 bugfix release has beed released a minute ago :)
