### ISSUE TITLE
[API Question] Mass Update with Profile ID - create new profile, when PROFILEID is missing

### ISSUE THREAD

**Issue by amenk** [SC-Networks/evalanche-soap-api-connector#179]
We call https://help.evalanche.cloud/hc/en-us/articles/360042265151-SOAP-Profile#massUpdate with `PROFILEID` as `key_attribute_name`. `ignore_missing` is false.

Some of our records already have a `PROFILEID`, some don't.
We want records without `PROFILEID` to be auto-created.

This does not seem to work ("error" is returned for the line)

When matching with another field, such as EMAIL, it works as expected (profiles for new mails are created, others are updated)

Is this possible in general for IDs as well, or do we have to make two calls, one for the already existing profiles and another one for the new ones?

**Comment by usox** [comment]
Hi @amenk 

Thanks, to me this looks like an issue regarding the api functionality which seems to require more work then just a quick look in the sources.
I'm sorry, but you've to file an official support request within the software. We can only support connector-related issues in here (although we will answer simple api related questions as well).

**Comment by amenk** [comment]
Okay, I forwarded the issue to the support.

**Comment by usox** [comment]
@amenk Thanks and sorry again.

**Comment by amenk** [comment]
It's alright, absolutely no need to be sorry :-)

Support asked for the exact request. What is the easiest way to export that? Is the specific support in the connector? Or do we have to patch the SOAP client temporarily.

**Comment by usox** [comment]
@WorksDev can you please take a look? Thanks.

**Comment by WorksDev** [comment]
Hello @amenk,

I don't know exactly what your profile update hashmap looks like, but if you set the profile id to 0, a new profile will be created with a new profile id. It is important to send this new profile ID the next time, otherwise the profile will be created again.

`->createProfileClient()->massUpdate(
	1,
	'PROFILEID',
	['EMAIL', 'PROFILEID'],
	[
		['roedl@example.com', 0],
		['roedl2@example.com', 123]
	],
	false,
	false
);`

**Comment by usox** [comment]
@amenk 

From what I know, there actually is a possibility to retrieve the request xml (and more).

Our soap client extends the native php soap client so you should have access to the native debugging methods like `__getLastRequest` (https://www.php.net/manual/de/soapclient.getlastrequest.php) and such. Those methods will only work if `trace` is enabled in the soap client options though (we enable it automatically if the debug mode is turned on in EvalancheConfig).

This may help you to perform the `deep dive` into the request data in such cases :smile:

**Comment by amenk** [comment]
Thanks everyone, we will probably work with the external identifier in the future, that might simplify things.

**Comment by usox** [comment]
@amenk kk.
fyi: Make sure you use the `EXTERNAL_ID` column for your external identifier. This one has special optimizations and will be much more performant compared to a custom string column.

**Comment by amenk** [comment]
For future readers:

\Scn\EvalancheSoapApiConnector\EvalancheSoapClient

    public function __construct(string $wsdl, array $options, bool $debugMode = false)
    {
        $options['trace'] = true;


...

    public function __call($method, $arguments = [])
    {
        try {
            $result = $this->__soapCall($method, $arguments);

            echo 'REQUEST:' . PHP_EOL;
            echo $this->__getLastRequest();
            echo 'RESPONSE:' . PHP_EOL;
            echo $this->__getLastResponse();

            return $result;
