### ISSUE TITLE
Any way to retrieve article type id from article?

### ISSUE THREAD

**Issue by attrib** [SC-Networks/evalanche-soap-api-connector#191]
When creating an article I use the id of a article type to define which fields are available:

`EvalancheResourceInformation create (int article_preset_id, string name, EvalancheHashMap data, int category_id)`

When fetching data, I do not get back which article type id it is, so which fields to expect in the response.

Is there a way to retrieve article type id for a article?

Also would be nice to have a method to retrieve articles by article type id.

**Comment by usox** [comment]
Hi @attrib 

Uhm yeah, your're right. Currently, there's no possibility to retrieve those informations. The retrieval-methods of articles (and containers) return ResourceInformation properties which contain just generic data - only the mailing-retrieval methods provide a extented property with more mailing specific data.

I'll get in touch with the team - in theory, it should be possible to extend the result of those retrieval methods like we did with the mailing. But maybe it could lead to some wsdl-related problems as the result property classes will change. We have to check this.

Regarding a retrieval method for articles using the type-id: That should'nt be a problem.

**Comment by usox** [comment]
For internal reference: EV-11688, EV-11689

**Comment by usox** [comment]
Hi @attrib 

We released a set of new methods within the api today (which are not documented yet). The linked changeset here and another upcoming one will contain the necessary additions to the connector.
We're expecting the release of a new connector version next week.

**Comment by usox** [comment]
HI @attrib 

The new methods have been released within 1.11.0

**Comment by attrib** [comment]
Thx. Already tested them yesterday with master and seems to work. But good that I can change to release version.
