### ISSUE TITLE
ProfileClient getByKey vs getByPool

### ISSUE THREAD

**Issue by paulboenisch** [SC-Networks/evalanche-soap-api-connector#33]
Hello, SC-Networks,

is it possible to get all pool profiles at once, including DELETED profiles?

**Comment by usox** [comment]
Hi Paul

Both, `ProfileClient` and `getByPool` should return all profiles including the deleted (= unsubscribed) ones. `getByPool` is the recommended way if you plan to retrieve the profiles more often.
