### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by version854** [SC-Networks/evalanche-soap-api-connector#40]
i created a file in the root with 

but when i open it i just get 

$connection = \Scn\EvalancheSoapApiConnector\EvalancheConnection::create(
    'given host',
    'given username',
    'given password'
);

Fatal error: Uncaught Error: Class 'Scn\EvalancheSoapApiConnector\EvalancheConnection' not found in /var/www/html/index.php:2 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 2

can someone tell me how to fix it, thanks

**Comment by WorksDev** [comment]
The autoload file must be included first.

```
require 'vendor/autoload.php';

....
```

**Comment by usox** [comment]
@version854 Hi. This connector uses the official php package manager called `composer`.
Please see the official php (https://www.php.net) and composer (https://getcomposer.org) documentation for php and programming related questions. If you have further questions regarding the usage of the connector, we're happy to help. Thank you for your understanding.
