### ISSUE TITLE
deleting an attribute from pool

### ISSUE THREAD

**Issue by ChrisB9** [SC-Networks/evalanche-soap-api-connector#45]
Hey
Thank you already for providing this really helpful package.

I am currently working on a little service to manage attributes and realized, that there isn't mentioned any way of removing an attribute from the pool

This is really sad, because i added an integration test for the "add attribute" method and it obviously after the second run says "attribute already exists" - catching this will make this test risky which i want to prevent. 

Is it possible to add this method?

**Comment by usox** [comment]
Hi and thanks for the feedback.

Well, it looks like it's not a big deal to add this method. Actually deleting attributes can be a thing though, because a user can't retrieve dependency relations at the moment. Maybe we will provide a separate method for that task afterwards...

**Comment by usox** [comment]
I filed an internal task for this.

**Comment by ChrisB9** [comment]
I am excited and look forward to this, thank you!

With dependency relations you mean those objects that are using the said attribute?

**Comment by usox** [comment]
> With dependency relations you mean those objects that are using the said attribute?

Right. Those attributes can be used in several places in the software, so there's a given chance the attribute won't be deletable (e.g. it's used in target groups, ...). But we'll see how this will work out ;)

**Comment by ChrisB9** [comment]
Alright, sounds good - let me know when you know more :)

**Comment by ChrisB9** [comment]
I stumbled upon another "issue" regarding the attributes or rather its options:
- My client wants to automatically add new Options to his Pool through our interface. I figured, that adding Options is only possible for the Option-Types Single and Multiselect, but i now get the Response, that the "PoolAttribute does not allow options to be added". I thought maybe the TypeId i used are wrong, but on the the website i can then modify that newly added attribute and add options.
Additionally i cannot modify an existing attribute and give it a new typeId - did i just not see this in the documentation or is this only possible through csv import / website?

**Comment by usox** [comment]
@worksdev any thoughts on this?

**Comment by WorksDev** [comment]
@usox not really - tried and tested and it is functional. @ChrisB9 could you paste the relevant part of your code?

**Comment by ChrisB9** [comment]
Once i copied the code, i saw the mistake i made. One should be able to write the actual Attribute Name correctly :)

Now, this is working 
`$name = 'TEST_ATTRIBUTE_8';
        $attribute = new PoolAttribute(null, 8, $name, 'Test-Attribut No. 8');
        $evalancheApiConnector->addAttributeToPool($this->connection, $attribute);
        $attribute = $evalancheApiConnector->getAttributeByName($this->connection, $name);
        $option = new PoolAttributeOption(null, 'TEST_ATTRIBUTE_OPTION');
        $updatedAttribute = $evalancheApiConnector->addOptionToAttribute($this->connection, $attribute, $option);`

**Comment by ChrisB9** [comment]
First of all, this package is really helpful when communicating with evalanche - works like a charm!
i just have one remaining question and am sorry that i am pretty much abusing this issue for all my questions! 
I wanted to then use the mass update functionality: 
```
massUpdate(
	int <pool-id>,
	string <key-pool-attribute-name>,
	string[] <pool-attribute-names>,
	HashMap[] <data>,
	bool <merge>,
	bool <ignore-missing>
): MassUpdateResult
```
i have some troubles understanding how this method works because MassUpdateResult contains only empty HashMaps and i have the feeling that i again did provide some wrong data or that the hash map is not how it is supposed to be ( i assumed, it is the exact same to create profile )
My first guess: I provide the pool-id, and also say with what i want to identify existing profiles (So on my first try i'd pass "EMAIL" as my key-attribute). Then the Array of Attribute-Strings analogue to creating a profile, then hashmap as stated above, and then i set merge to true (as i want my dataset to be updated?) and ignore-missing to false because i want new data to be created

Thank you already so much for helping me out a lot, you guys really saved my last days

**Comment by usox** [comment]
The internal changes for the new api method passed QA today, scheduled rollout is next friday. I guess, the final changes in the connector will be released later this month.

**Comment by ChrisB9** [comment]
That is amazing! Thank you!

**Comment by WorksDev** [comment]
@ChrisB9 Release 1.2.0 contains the desired feature. Thanks for your feedback.

**Comment by ChrisB9** [comment]
Thank you, we will incorporate that in our next sprint then!
