### ISSUE TITLE
MassUpdate does not seem to work as expected

### ISSUE THREAD

**Issue by ChrisB9** [SC-Networks/evalanche-soap-api-connector#46]
First of all, this package is really helpful when communicating with evalanche - works like a charm with one exception: massUpdate
I wanted to then use the mass update functionality:

massUpdate(
	int <pool-id>,
	string <key-pool-attribute-name>,
	string[] <pool-attribute-names>,
	HashMap[] <data>,
	bool <merge>,
	bool <ignore-missing>
): MassUpdateResult
i have some troubles understanding how this method works because MassUpdateResult contains only empty HashMaps and i have the feeling that i again did provide some wrong data or that the hash map is not how it is supposed to be ( i assumed, it is the exact same to create profile )
My first guess: I provide the pool-id, and also say with what i want to identify existing profiles (So on my first try i'd pass "EMAIL" as my key-attribute). Then the Array of Attribute-Strings analogue to creating a profile, then hashmap as stated above, and then i set merge to true (as i want my dataset to be updated?) and ignore-missing to false because i want new data to be created

I analyzed the problem from above a little further and realized, that the massUpdate in the documentation does not align with the phpDoc of the function, nor its implemented test:
```php
// doc 

 /**
     * @param int $id
     * @param string $keyAttributeTitle
     * @param string[] $attributes
     * @param string[] $data
     * @param bool $merge
     * @param bool $ignoreMissing
     *
     * @return MassUpdateResultInterface
     * @throws EmptyResultException
     */
    public function massUpdate(
        int $id,
        string $keyAttributeTitle,
        array $attributes,
        array $data,
        bool $merge,
        bool $ignoreMissing
    ): MassUpdateResultInterface

// test

$id = 4;
        $keyAttributeTitle = 's-o-m-e t-i-t-l-e';
        $attributes = [
            'attribute a',
            'attribute b',
            'attribute c',
        ];
        $data = [
            'data a',
            'data b',
            'data c'
        ];
        $merge = false;
        $ignoreMissing = true;

 ```
$data should be a hashMap according to the documentation but it seems to be a string[]. Later does not provide me the possibility to identify nor update multiple profiles but a hashmap would
Also a hashmap would be more consistent to the other functionality

i then thought to wrap data with the extractor from the other functionalities:

```php

 $this->extractor->extract($this->hydratorConfigFactory->createHashMapConfig(), $hashMap);
foreach ($data as $hashMap) {
    $result[] = $this->extractor->extract($this->hydratorConfigFactory->createHashMapConfig(), $hashMap);
}

```

but sending that result as payload to evalanche didnt work either

i am now super clueless as how to handle this. @WorksDev do you have any idea 

Thank you already so much for helping me out a lot, you guys really saved my last days

**Comment by WorksDev** [comment]
@ChrisB9 you are right the documentation is wrong at this point - correctly it is a string[][] - so it is possible to update multiple profiles

e.g.

```
        [
            ['test1@test1.de', someId],
            ['test2@test2.de', someOtherId],
            .....
        ],
```
Regarding your further questions - a detailed description what these parameters do can be found in the ServiceCenter.

Hope that helps.

**Comment by usox** [comment]
Thanks for pointing this out

**Comment by ChrisB9** [comment]
Yea! Now it works :+1:
