### ISSUE TITLE
Problem retrieving article by ID

### ISSUE THREAD

**Issue by s1de** [SC-Networks/evalanche-soap-api-connector#52]
Hey,

i try to get an article by his id, but i really struggle with it.

I installed it via composer and this is my file in root:

```
<?php
require 'vendor/autoload.php';

$connection = \Scn\EvalancheSoapApiConnector\EvalancheConnection::create(
    'my host',
    'my user',
    'my pw',
    true
);
    
$getArticle = $connection->createArticleClient()->getDetailById(123);

```

My response is:
`
Fatal error: Uncaught TypeError: Argument 1 passed to Scn\EvalancheSoapApiConnector\Mapper\ResponseMapper::getObject() must be an instance of Scn\EvalancheSoapApiConnector\Mapper\object, instance of stdClass given, called in /htdocs/evalanche-soap-api-connector/vendor/scn/evalanche-soap-api-connector/src/Client/Article/ArticleClient.php on line 69 and defined in /htdocs/evalanche-soap-api-connector/vendor/scn/evalanche-soap-api-connector/src/Mapper/ResponseMapper.php:110 Stack trace: #0 /htdocs/evalanche-soap-api-connector/vendor/scn/evalanche-soap-api-connector/src/Client/Article/ArticleClient.php(69): Scn\EvalancheSoapApiConnector\Mapper\ResponseMapper->getObject(Object(stdClass), 'getDataResult', Object(Scn\EvalancheSoapApiConnector\Hydrator\Config\Generic\HashMapConfig)) #1 /htdocs/evalanche-soap-api-connector/index.php(16): Scn\EvalancheSoapApiConnector\Client\Article\ArticleClient->getDetailById(123) #2 {main} thrown in/htdocs/evalanche-soap-api-connector/vendor/scn/evalanche-soap-api-connector/src/Mapper/ResponseMapper.php on line 110
`

Hope someone can help me, thank you!

**Comment by WorksDev** [comment]
Here I need some more information, please send hostname / user / article ID to support@sc-networks.com. For the attention of S. Nützel.

**Comment by WorksDev** [comment]
@s1de your e-mail with the data has arrived, unfortunately the problem cannot be reconstructed. As expected, an object of the type HashMap is returned with the addressed code snippet (and the submitted Id). Could you try it again?

**Comment by s1de** [comment]
@WorksDev Thank you for your help, i've still the problem, with every call that should have a response...

**Comment by s1de** [comment]
@WorksDev ok, i just uploaded my files to my testserver and it's working. I can't really explain why it's not working on my local env. It's on php 7.1.8 ...

**Comment by WorksDev** [comment]
Thanks for the info - the PHP version is the problem. Minimum requirement is PHP >= 7.2 due to Strict Types
