### ISSUE TITLE
Using result for other function

### ISSUE THREAD

**Issue by s1de** [SC-Networks/evalanche-soap-api-connector#53]
Hey,

i've a function like this:

```
	$getFolder = $connection->createFolderClient()->create($FolderName, 123);
	echo $getFolder->id;
```
but `$getFolder->id` is private. Is there a function to get the results so i can use them to create an article with the predefined folder id?

Thanks in advance.

s1de

**Comment by WorksDev** [comment]
Please have a look at the return values, in this case a FolderInformationInterface will be returned containing the required methods (getId(), getName())
