### ISSUE TITLE
Inside pool which method to use for creating attribute category and how to assign new attribute to that category.

### ISSUE THREAD

**Issue by yash-patadia** [SC-Networks/evalanche-soap-api-connector#92]
Question :: Inside pool which method to use for creating attribute category and how to assign new attribute to that category ?

**Comment by WorksDev** [comment]
Hello @yash-patadia,

i hope i understand it correctly - there is no way to create "categories" for pool attributes.
To add attributes to a Pool 


```
$this->client->createPoolClient()->addAttribute(
	$pool_id,
	$name,
	$label,
	$type_id
);
```

Please also have a look at the documentation.
