### ISSUE TITLE
Profile massUpdate does not return change_date attribute

### ISSUE THREAD

**Issue by yash-patadia** [SC-Networks/evalanche-soap-api-connector#93]
Profile mass update does not return the change_date attribute.

The timestamp from when the Profile massUpdate is requested and the actual update of profile change_date timestamp differ, it would be better if in response massUpdatealso shares the change_date attribute.

**Comment by WorksDev** [comment]
Hello @yash-patadia ,

could you please explain in more detail what for and why? At the moment I don't think this makes much sense.

**Comment by yash-patadia** [comment]
Hi @WorksDev,

I'm using this SDK to sync subscriptions bidirectional lets say between Evalanche and System-A

- Evalanche override System-A subscription
- System-A override Evalanche subscription

Based on timestamp, so whenever System-A override Evalanche subscription using profile massUpdate method the request & response timestamp differ of lets assume 5 sec, System-A will miss subscriptions changes of this 5sec.

**Comment by WorksDev** [comment]
I think I understand the basic problem, but here this change would have to be shown in the profile - because otherwise there would be differences depending on the amount of data.

In my opinion it would be easiest to look / save when the request was sent and to base everything else on this timestamp?

@usox Opinion?

**Comment by usox** [comment]
Hm, an option would be to defer the update of the change date into a separate update after the profile data has been updated.
As I understand the problem, the amount of data leads to a longer running update process. So the actual timestamp of a profile differs from the end-date of the request. Am I getting this right?

**Comment by yash-patadia** [comment]
@usox yes that's the issue.

**Comment by usox** [comment]
We looked into that issue.
Any change in the current behaviour is considered a breaking change, so atm we won't change it. In a future api version of this method, we will come up with a solutation.
