### ISSUE TITLE
Profile grantPermission method does not update any date field

### ISSUE THREAD

**Issue by yash-patadia** [SC-Networks/evalanche-soap-api-connector#95]
Profile grantPermission method does not update any date field, then how can we found at what exact timestamp this change was happening?

**Comment by WorksDev** [comment]
Hello @yash-patadia ,

currently not at all - as a workaround, however, a grantPermission with subsequent updateProfiles would be possible.

I have included this in the requirements, and we will discuss it internally.

@usox , what is the argument against outputting the changelog for the profiles, e.g. in a new method?

**Comment by usox** [comment]
@WorksDev @yash-patadia 
Well, not 100% correct. GrantPermission updates the "Permission-Date" attribute in the profile. Never the less we could discuss the option to make the complete changelog accessible.

**Comment by yash-patadia** [comment]
@usox 
While fetching the profile fields not able to find "Permission-Date" attribute I'm using **getAttributesByPool** method, is there any other method to get this attribute?

**Comment by usox** [comment]
@yash-patadia Sorry for the late reply. The "Permission-Date" is not an "official" attribute, it's an profile related information which is not part of the pool attribute list. All permission changes are saved within a per-profile-changelog which is not accessible by the api atm.
